// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: google/events/cloud/scheduler/v1/events.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";
import { JobEventData, SchedulerJobData } from "./data";

export const protobufPackage = "google.events.cloud.scheduler.v1";

/** The CloudEvent raised when a Job is created. */
export interface JobCreatedEvent {
  /** The data associated with the event. */
  data?: JobEventData | undefined;
}

/** The CloudEvent raised when a Job is updated. */
export interface JobUpdatedEvent {
  /** The data associated with the event. */
  data?: JobEventData | undefined;
}

/** The CloudEvent raised when a Job is deleted. */
export interface JobDeletedEvent {
  /** The data associated with the event. */
  data?: JobEventData | undefined;
}

/** The CloudEvent raised when a Scheduler job is executed. */
export interface JobExecutedEvent {
  /** The data associated with the event. */
  data?: SchedulerJobData | undefined;
}

function createBaseJobCreatedEvent(): JobCreatedEvent {
  return { data: undefined };
}

export const JobCreatedEvent: MessageFns<JobCreatedEvent> = {
  encode(message: JobCreatedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      JobEventData.encode(message.data, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobCreatedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobCreatedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = JobEventData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobCreatedEvent {
    return { data: isSet(object.data) ? JobEventData.fromJSON(object.data) : undefined };
  },

  toJSON(message: JobCreatedEvent): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = JobEventData.toJSON(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobCreatedEvent>, I>>(base?: I): JobCreatedEvent {
    return JobCreatedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobCreatedEvent>, I>>(object: I): JobCreatedEvent {
    const message = createBaseJobCreatedEvent();
    message.data = (object.data !== undefined && object.data !== null)
      ? JobEventData.fromPartial(object.data)
      : undefined;
    return message;
  },
};

function createBaseJobUpdatedEvent(): JobUpdatedEvent {
  return { data: undefined };
}

export const JobUpdatedEvent: MessageFns<JobUpdatedEvent> = {
  encode(message: JobUpdatedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      JobEventData.encode(message.data, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobUpdatedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobUpdatedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = JobEventData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobUpdatedEvent {
    return { data: isSet(object.data) ? JobEventData.fromJSON(object.data) : undefined };
  },

  toJSON(message: JobUpdatedEvent): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = JobEventData.toJSON(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobUpdatedEvent>, I>>(base?: I): JobUpdatedEvent {
    return JobUpdatedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobUpdatedEvent>, I>>(object: I): JobUpdatedEvent {
    const message = createBaseJobUpdatedEvent();
    message.data = (object.data !== undefined && object.data !== null)
      ? JobEventData.fromPartial(object.data)
      : undefined;
    return message;
  },
};

function createBaseJobDeletedEvent(): JobDeletedEvent {
  return { data: undefined };
}

export const JobDeletedEvent: MessageFns<JobDeletedEvent> = {
  encode(message: JobDeletedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      JobEventData.encode(message.data, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobDeletedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobDeletedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = JobEventData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobDeletedEvent {
    return { data: isSet(object.data) ? JobEventData.fromJSON(object.data) : undefined };
  },

  toJSON(message: JobDeletedEvent): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = JobEventData.toJSON(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobDeletedEvent>, I>>(base?: I): JobDeletedEvent {
    return JobDeletedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobDeletedEvent>, I>>(object: I): JobDeletedEvent {
    const message = createBaseJobDeletedEvent();
    message.data = (object.data !== undefined && object.data !== null)
      ? JobEventData.fromPartial(object.data)
      : undefined;
    return message;
  },
};

function createBaseJobExecutedEvent(): JobExecutedEvent {
  return { data: undefined };
}

export const JobExecutedEvent: MessageFns<JobExecutedEvent> = {
  encode(message: JobExecutedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      SchedulerJobData.encode(message.data, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobExecutedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobExecutedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = SchedulerJobData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobExecutedEvent {
    return { data: isSet(object.data) ? SchedulerJobData.fromJSON(object.data) : undefined };
  },

  toJSON(message: JobExecutedEvent): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = SchedulerJobData.toJSON(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobExecutedEvent>, I>>(base?: I): JobExecutedEvent {
    return JobExecutedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobExecutedEvent>, I>>(object: I): JobExecutedEvent {
    const message = createBaseJobExecutedEvent();
    message.data = (object.data !== undefined && object.data !== null)
      ? SchedulerJobData.fromPartial(object.data)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
