// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: google/events/cloud/dataflow/v1beta3/events.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";
import { JobEventData } from "./data";

export const protobufPackage = "google.events.cloud.dataflow.v1beta3";

/** The CloudEvent raised when a Job status changes. */
export interface JobStatusChangedEvent {
  /** The data associated with the event. */
  data?: JobEventData | undefined;
}

function createBaseJobStatusChangedEvent(): JobStatusChangedEvent {
  return { data: undefined };
}

export const JobStatusChangedEvent: MessageFns<JobStatusChangedEvent> = {
  encode(message: JobStatusChangedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      JobEventData.encode(message.data, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobStatusChangedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobStatusChangedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = JobEventData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobStatusChangedEvent {
    return { data: isSet(object.data) ? JobEventData.fromJSON(object.data) : undefined };
  },

  toJSON(message: JobStatusChangedEvent): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = JobEventData.toJSON(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobStatusChangedEvent>, I>>(base?: I): JobStatusChangedEvent {
    return JobStatusChangedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobStatusChangedEvent>, I>>(object: I): JobStatusChangedEvent {
    const message = createBaseJobStatusChangedEvent();
    message.data = (object.data !== undefined && object.data !== null)
      ? JobEventData.fromPartial(object.data)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
